### ISSUE TITLE
Subscriber list look-up

### ISSUE THREAD

**Issue by chainhead** [beckn-on-succinct/beckn-gateway#1]
How large do you estimate the `subscriberList` to be in production? Refer [here](https://github.com/venkatramanm/beckn-gateway/blob/5141a2d94256411eb7b9989122519bea2f3de398/src/main/java/in/succinct/beckn/gateway/controller/BgController.java#L141) and [here](https://github.com/venkatramanm/beckn-gateway/blob/5141a2d94256411eb7b9989122519bea2f3de398/src/main/java/in/succinct/beckn/gateway/controller/BgController.java#L155).

**Comment by venkatramanm** [comment]
In hundreds per domain. While this is a reference bg, There are definite plans of enhancing the gateway protocol to have recursive propagations to avoid large number of subscribers to be transmitted to.
