### ISSUE TITLE
Events from Gateway

### ISSUE THREAD

**Issue by invinayak007** [beckn-on-succinct/beckn-gateway#2]
In order to use cQube as a dashboard, events need to be emitted from the gateway. Below are some initial details on this.

Data required for cQube

Metrics : Registrations, Search calls, Broadcasts,
Dimensions : Domain, Location, Date, Hour of the day, Location, Platform

Typical Events

Registration details along with domain, location, time and platform
Search details with domain, location, time and platform
broadcast details with domain, location, time and platform

**Comment by venkatramanm** [comment]
We are emitting events "on_subscriber_update"  on registry and "bg_request" from gateway now. 
You will however need to configure applications like "cqube" on the bg and registry under /applications and configure event_handlers to restful urls relative to application endpoints where such events are published. 

app_id and secret attributes of application are used to construct basic auth while calling from the application, And the client_id and secret configured at the app endpoint is used to send such events to the application (from bg or registry).

**Comment by venkatramanm** [comment]
https://github.com/beckn-on-succinct/beckn-gateway/commit/5cea724d80ae94da835f97419e947b571b9075d3?diff=split
